Added videos for meetup-4.0.0
DesignSystemMeetup/design-system-website pull request #5
Opened 2018-10-01 19:36 UTC by alex-e-leon

2018-10-01 19:37 UTC, alex-e-leon commented
Also would be dope if I could get permission to this repo so I don't have to keep my own fork up to date : )

2018-10-04 11:26 UTC, dominikwilkowski requested changes

2018-10-04 11:26 UTC, dominikwilkowski commented on code/assets/css/site.min.css
> -html{height:100%}body{-moz-osx-font-smoothing:grayscale;-ms-text-size-adjust:100%;-webkit-font-smoothing:antialiased;-webkit-text-size-adjust:100%;background:#0a0f2b;color:#d9e5ff;font-family:-apple-
apparently the prefixer didn't run here... I'll merge when I get the consents and run build again...

2018-10-04 11:26 UTC, alex-e-leon commented on code/assets/css/site.min.css
> -html{height:100%}body{-moz-osx-font-smoothing:grayscale;-ms-text-size-adjust:100%;-webkit-font-smoothing:antialiased;-webkit-text-size-adjust:100%;background:#0a0f2b;color:#d9e5ff;font-family:-apple-
👍

2018-10-08 02:55 UTC, dominikwilkowski approved these changes

2018-10-08 02:55 UTC, merged