Service Worker
DesignSystemMeetup/design-system-website pull request #7
Opened 2018-11-29 23:24 UTC by nathansimpsondesign

2018-12-01 00:24 UTC, dominikwilkowski requested changes
Hey @nathansimpsondesign 
Thank you for all this work. Looks very good and is close. I added some notes here and there. Let's go over them together.
Have a good weekend.

2018-12-01 00:24 UTC, dominikwilkowski commented on code/assets/js/script.min.js
> +/*
Need to reenable google analytics here

2018-12-01 00:24 UTC, dominikwilkowski commented on code/assets/js/script.min.js
> +async function init(){
We need to test if service workers are supported here first.

2018-12-01 00:24 UTC, dominikwilkowski commented on code/assets/js/script.min.js
> +	registration = await navigator.serviceWorker.register('/sw.min.js')
`try` `catch` missing

2018-12-01 00:24 UTC, dominikwilkowski commented on code/assets/js/script.min.js
> +			console.log(this.state);
needs to be removed for production

2018-12-01 00:24 UTC, dominikwilkowski commented on code/assets/js/script.min.js
> +	init();
A self calling function might be better or do the promise chain as I had it before

2018-12-01 00:24 UTC, dominikwilkowski commented on code/assets/js/sw.template.js
> +		caches.open($name).then(cache => {
Can we make the template variables more visible so the script fails if it runs without templating? Something like `<<NAME>>` or `{{NAME}}` or something.
So this line would look like:
```js
caches.open(<<NAME>>).then(cache => {
```

2018-12-01 00:24 UTC, dominikwilkowski commented on code/assets/js/sw.template.js
> +self.onactivate = evt => {
I'm a big proponent of naming variables in a human way. What does `evt` stand for? Should we name it a real word?

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +const fs = require("fs");
single quotes please

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +function read(dir) {
Definitely needs a better function name

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +			if(item !== ''){filesToCache.push(`"${item}"`)}
you just assigned `item` with a string. This condition can never be false

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +		}else if(!child.includes('CNAME')){
what about `.` files?

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +read('docs');
Have a look at this function:
https://github.com/cuttlebelle/cuttlebelle/blob/master/src/site.js?ts=2#L37
There is a function that crawls a file system and returns all folders/files.

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +fs.readFile('code/assets/js/sw.template.js', 'utf8', function(err, template) {
You put the above thing into a function and this is executed directly with a hardcoded value. Let's check together how we might make this a bit more structured.

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +let filesToCache = ['"/"']
You don't need the quotes. Use `JSON.stringify` or something else when replacing

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +	fs.writeFile("docs/assets/js/sw.min.js", file, function(err) {
I would use an arrow function here and everywhere in this file

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +		.replace(/^\s*[\r\n]/gm, '');
your way of minifying? Leaves a lot of white space still. Worth using an actual minifier?

2018-12-01 00:24 UTC, dominikwilkowski commented on code/layout/helper.js
> +	console.log(`/${ ID === 'index' ? '.' : ID }/`, ' ', `/${ URL }`, ' --> ' , relative);
definitely don't need that console log anymore

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +	//console.log('Service worker will cache these files...', filesToCache);
No need for console logs in the git history

2018-12-01 00:24 UTC, dominikwilkowski commented on code/layout/page.js
> +				<Scripts _ID={ _ID } _relativeURL={ RelativeURL }/>
since we removed this prop in `script.js` we don't need this anymore

2018-12-01 00:24 UTC, dominikwilkowski commented on code/layout/page.js
> +			<Head _ID={ _ID } _relativeURL={ RelativeURL } pagetitle={ pagetitle }/>
No need for this prop anymore since Head is now importing it directly

2018-12-01 00:24 UTC, dominikwilkowski commented on code/layout/event.js
> +		<Head _ID={ _ID } _relativeURL={ RelativeURL } pagetitle={ pagetitle }/>
no need

2018-12-01 00:24 UTC, dominikwilkowski commented on code/layout/event.js
> -							_relativeURL={ _relativeURL }
no need

2018-12-01 00:24 UTC, dominikwilkowski commented on code/layout/event.js
> +			<Scripts _ID={ _ID } _relativeURL={ RelativeURL }/>
can go

2018-12-01 00:24 UTC, dominikwilkowski commented on code/layout/homepage.js
> +			<Head _ID={ _ID } _relativeURL={ RelativeURL } pagetitle={ pagetitle }/>
can go

2018-12-01 00:24 UTC, dominikwilkowski commented on code/layout/homepage.js
> +							_relativeURL={ RelativeURL }
can go

2018-12-01 00:24 UTC, dominikwilkowski commented on code/layout/homepage.js
> +				<Scripts _ID={ _ID } _relativeURL={ RelativeURL }/>
can go

2018-12-01 00:24 UTC, dominikwilkowski commented on content/index/index.yml
> +  city: Sydney CBD
why the change?

2018-12-01 00:24 UTC, dominikwilkowski commented on docs/assets/js/sw.min.js
> +			return cache.addAll("/","/assets/css/site.min.css","/assets/favicons/android-chrome-192x192.png","/assets/favicons/android-chrome-512x512.png","/assets/favicons/apple-touch-icon.png","/assets/favi
need to exclude the service worker file

2018-12-01 00:24 UTC, dominikwilkowski commented on docs/assets/js/sw.min.js
> +			return cache.addAll("/","/assets/css/site.min.css","/assets/favicons/android-chrome-192x192.png","/assets/favicons/android-chrome-512x512.png","/assets/favicons/apple-touch-icon.png","/assets/favi
Also don't need the template

2018-12-01 00:24 UTC, dominikwilkowski commented on docs/assets/js/sw.template.js
> +self.oninstall = evt => {
This should no end up in the docs folder. Needs to be either git ignored or handled differently

2018-12-01 00:24 UTC, dominikwilkowski commented on docs/sw.min.js
> +const VERSION = '0.1.1';
What's with this file? Now we have two SW?

2018-12-01 00:24 UTC, dominikwilkowski commented on yarn.lock
> +  integrity sha512-bPHp6Ji8b41szTOcaP63VlnbbO5Ny6dwAATtY6JTjh5N2OLrb5Qk/Th5cRkRQhkWCt+EJsYrNB0MiL+Gpn6e3g==
Let's not make unnecessary changes to the lock file. Please revert

2018-12-01 00:24 UTC, dominikwilkowski commented on code/helper/sw.js
> +	fs.writeFile("docs/assets/js/sw.min.js", file, function(err) {
That;s also the wrong place to write it out to. Service workers need to be in the root of the website. `docs/sw.min.js`

2018-12-01 00:24 UTC, dominikwilkowski commented on code/assets/js/script.min.js
> +	registration = await navigator.serviceWorker.register('/sw.min.js')
And you moved the service worker to another folder. This path is right but it now points to the old SW

2018-12-02 22:48 UTC, nathansimpsondesign commented on content/index/index.yml
> +  city: Sydney CBD
resolved

2018-12-05 07:07 UTC, dominikwilkowski requested changes
Move to helper `relativeURL` and remove promise in `sw.js`

2018-12-05 07:07 UTC, dominikwilkowski commented on code/assets/js/sw.template.js
> +			return cache.addAll([$filesToCache]);
should be two curlies
```suggestion
			return cache.addAll([{{filesToCache}}]);
```

2018-12-05 07:07 UTC, dominikwilkowski commented on code/helper/sw.js
> +					.replace(/\$filesToCache/g, filesToCache)
fix me

2018-12-05 07:07 UTC, dominikwilkowski commented on code/helper/sw.js
> +				let file = template
```suggestion
				const file = template
```

2018-12-05 07:07 UTC, dominikwilkowski commented on code/helper/sw.js
> +			fs.readFile('code/assets/js/sw.template.js', 'utf8', (err, template) => {
should probably use `readFileSync`

2018-12-05 07:07 UTC, dominikwilkowski commented on code/layout/eventDetails.js
> +	_relativeURL,
should us the helpers `relativeURL`

2018-12-05 23:11 UTC, dominikwilkowski requested changes

2018-12-05 23:11 UTC, dominikwilkowski commented on code/helper/sw.js
> +					.replace(/^\s*[\r\n]/gm, '');
maybe use uglify2?

2018-12-05 23:11 UTC, dominikwilkowski commented on code/assets/js/sw.template.js
> +			return cache.addAll([{{filesToCache}}]);
Let's do the same as with `{{NAME}}`.

```suggestion
			return cache.addAll([{{FILES}}]);
```

2018-12-06 22:30 UTC, dominikwilkowski requested changes
So close! Good work!

2018-12-06 22:30 UTC, dominikwilkowski commented on code/helper/sw.js
> +fs.writeFileSync('docs/sw.min.js', sw_file, error => {if (error) console.log(error);});
The third argument for `writeFileSync` is `options`
https://nodejs.org/api/fs.html#fs_fs_writefilesync_file_data_options

However `fs_writefile` does have a FORTH argument for callback functions.
https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback

It does not take a function

2018-12-06 22:30 UTC, dominikwilkowski commented on code/helper/sw.js
> +	let minified = minify(template);
```suggestion
	const minified = minify(template);
```

2018-12-07 05:22 UTC, merged